language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4.2"
before_script:
  - npm install -g mocha
  - npm install -g eslint
  - npm i coveralls --save-dev
script: npm test
bundler_args: --retry 2
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
after_script:
    - npm run coveralls
notifications:
  slack: ecmadao:fKFA5rnMSWRUqZrA9bS3gaD2
